package com.minimart.model;

// Generated Aug 12, 2014 10:36:52 PM by Hibernate Tools 3.4.0.CR1

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;

import javax.xml.bind.annotation.XmlRootElement;

import com.minimart.annotation.POSFieldAnnotation;
import com.minimart.annotation.POSModelAnnotation;

/**
 * InventoryItem generated by hbm2java
 */
@POSModelAnnotation(dbTableName="INVENTORY_ITEM")
@XmlRootElement
public class InventoryItem extends POSModel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3092764055008072741L;

	/**
	 * @param id
	 * @param productId
	 * @param trackingCode
	 * @param quantity
	 * @param receivedDate
	 * @param expiryDate
	 * @param promotionalOffer
	 */
	public InventoryItem(Integer id, Integer productId, String trackingCode,
			int quantity, Date receivedDate, Date expiryDate,
			String promotionalOffer) {
		super();
		this.id = id;
		this.productId = productId;
		this.trackingCode = trackingCode;
		this.quantity = quantity;
		this.receivedDate = receivedDate;
		this.expiryDate = expiryDate;
		this.promotionalOffer = promotionalOffer;
	}

	@POSFieldAnnotation(dbColumnName = "id")
	private Integer id;

	@POSFieldAnnotation(dbColumnName = "product_id")
	private Integer productId;

	@POSFieldAnnotation(dbColumnName = "tracking_code")
	private String trackingCode;
	
	@POSFieldAnnotation(dbColumnName = "quantity")
	private int quantity;

	@POSFieldAnnotation(dbColumnName = "received_date")
	private Date receivedDate;

	@POSFieldAnnotation(dbColumnName = "expiry_date")
	private Date expiryDate;
	
	@POSFieldAnnotation(dbColumnName = "promotional_offer")
	private String promotionalOffer;

	/**
	 * @return the id
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * @return the productId
	 */
	public Integer getProductId() {
		return productId;
	}

	/**
	 * @param productId the productId to set
	 */
	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	/**
	 * @return the trackingCode
	 */
	public String getTrackingCode() {
		return trackingCode;
	}

	/**
	 * @param trackingCode the trackingCode to set
	 */
	public void setTrackingCode(String trackingCode) {
		this.trackingCode = trackingCode;
	}

	/**
	 * @return the quantity
	 */
	public int getQuantity() {
		return quantity;
	}

	/**
	 * @param quantity the quantity to set
	 */
	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	/**
	 * @return the receivedDate
	 */
	public Date getReceivedDate() {
		return receivedDate;
	}

	/**
	 * @param receivedDate the receivedDate to set
	 */
	public void setReceivedDate(Date receivedDate) {
		this.receivedDate = receivedDate;
	}

	/**
	 * @return the expiryDate
	 */
	public Date getExpiryDate() {
		return expiryDate;
	}

	/**
	 * @param expiryDate the expiryDate to set
	 */
	public void setExpiryDate(Date expiryDate) {
		this.expiryDate = expiryDate;
	}

	/**
	 * @return the promotionalOffer
	 */
	public String getPromotionalOffer() {
		return promotionalOffer;
	}

	/**
	 * @param promotionalOffer the promotionalOffer to set
	 */
	public void setPromotionalOffer(String promotionalOffer) {
		this.promotionalOffer = promotionalOffer;
	}

	/**
	 * 
	 */
	public InventoryItem() {
		super();
		// TODO Auto-generated constructor stub
	}

	@Override
	public void loadFromResultSet(ResultSet resultSet) throws SQLException {
		
		this.id = resultSet.getInt("id");
		this.productId = resultSet.getInt("product_id");
		this.trackingCode = resultSet.getString("tracking_code");
		this.quantity = resultSet.getInt("quantity");
		this.receivedDate = resultSet.getDate("received_date");
		this.expiryDate = resultSet.getDate("expiry_date");
		this.promotionalOffer = resultSet.getString("promotional_offer");
	}

	@Override
	public Object[] toObjectArray(boolean includeId) {

		if (includeId) {
			Object[] params = { this.productId, this.trackingCode, this.quantity, this.receivedDate, this.expiryDate, this.promotionalOffer, this.id};
			return params;
		} else {
			Object[] params = { this.productId, this.trackingCode, this.quantity, this.receivedDate, this.expiryDate, this.promotionalOffer};
			return params;
		}
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((expiryDate == null) ? 0 : expiryDate.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result
				+ ((productId == null) ? 0 : productId.hashCode());
		result = prime
				* result
				+ ((promotionalOffer == null) ? 0 : promotionalOffer.hashCode());
		result = prime * result + quantity;
		result = prime * result
				+ ((receivedDate == null) ? 0 : receivedDate.hashCode());
		result = prime * result
				+ ((trackingCode == null) ? 0 : trackingCode.hashCode());
		return result;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof InventoryItem)) {
			return false;
		}
		InventoryItem other = (InventoryItem) obj;
		if (expiryDate == null) {
			if (other.expiryDate != null) {
				return false;
			}
		} else if (!expiryDate.equals(other.expiryDate)) {
			return false;
		}
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		if (productId == null) {
			if (other.productId != null) {
				return false;
			}
		} else if (!productId.equals(other.productId)) {
			return false;
		}
		if (promotionalOffer == null) {
			if (other.promotionalOffer != null) {
				return false;
			}
		} else if (!promotionalOffer.equals(other.promotionalOffer)) {
			return false;
		}
		if (quantity != other.quantity) {
			return false;
		}
		if (receivedDate == null) {
			if (other.receivedDate != null) {
				return false;
			}
		} else if (!receivedDate.equals(other.receivedDate)) {
			return false;
		}
		if (trackingCode == null) {
			if (other.trackingCode != null) {
				return false;
			}
		} else if (!trackingCode.equals(other.trackingCode)) {
			return false;
		}
		return true;
	}
	
	
}
